Feat/comment api
SSSSoGong/issue-itsue-server pull request #17
Opened 2024-05-26 06:49 UTC by yjg0815

1. mapper 생성 후 service에 적용

2. domain, repository, service 관련 테스트 작성 
  => security 관련 @WithMockUser 사용 
  => 통과 완

3. CommentPrivilegeEvaluator 관련 update, delete  메서드에 적용 
  => PreAuthorize가 파라미터의 commentId를 인식 못하는 이슈 발생
  => @P("파라미터 이름") 붙여서 해결

==> 포스트맨에서 api  잘 작동하는거 확인 완료 <==

2024-05-26 08:57 UTC, ja7811 approved these changes
👍 
@P는 왜 써야되는지 잘 모르겠음
다른 예제에서는 잘 되던데 허허..
찾아봐도 잘 안나오네요

암튼 @PreAuthorize 잘 작동한 거 맞죠?
굿입니다

2024-05-26 10:02 UTC, ja7811 requested changes
근데 AdminRepositoryTest 충돌난 거 같은데

2024-05-26 12:06 UTC, yjg0815 commented
> 근데 AdminRepositoryTest 충돌난 거 같은데

나 안건드렸는데
내일 머지하면서 지우자

2024-05-27 09:40 UTC, hectick approved these changes

2024-05-27 09:41 UTC, ja7811 approved these changes
해치웠나

2024-05-27 09:41 UTC, merged